[package]
name = "toppy-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
toppy-core = { path = "../toppy-core" }

clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
