[advisories]
version = 2
unmaintained = "workspace"
yanked = "warn"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "LGPL-2.1-or-later",
  "MIT",
  "MIT-0",
  "OpenSSL",
  "Unlicense",
  "Unicode-3.0",
  "Zlib",
]
